services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab_collector
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgadmin_data: {}